beginnerTup = ('Simple Quadegories for younger players or beginners',
 [['Pringles',
   'Tostitos',
   "Lay's",
   'Doritos',
   'Chip Brands',
   'The <em style="font-size:inherit">vanishing caloric density</em> is the phenomenon that snacks that melt in your mouth also trick your subconscious into thinking they don\'t contain calories.'],
  ['Hulu',
   'Netflix',
   'YouTube',
   'Amazon Prime Video',
   'Streaming Services',
   'Netflix has over 70 Million users.'],
  ['Cookies',
   'Cake',
   'Brownies',
   'Ice Cream',
   'Desserts',
   'The world’s largest wedding cake weighed 15,032 lb and was made by chefs at the Mohegan Sun Hotel and Casino, Uncasville, CT in February 2004.'],
  ['Razor',
   'LG',
   'Samsung',
   'Apple',
   'Cell Phone Companies',
   "The name 'Apple' came from founder Steve Jobs' like of the fruit"],
  ['Sleepy',
   'Grumpy',
   'Bashful',
   'Doc',
   'Dwarf Names',
   'Snow White and the 7 Dwarfs was the first full length movie from Walt Disney Studios.']])
