expertTup = ('Challenging Quadegories from an eclectic variety of sources',
 [['Pommes dauphin',
   'Clam cake',
   'Savory patty',
   'Egg roll',
   'Fried Foods',
   'The  <strong style="font-size:inherit">clam cake</strong> was invented at Aunt Carrie\'s, an award-winning Rhode Island restaurant, when Aunt Carrie added fresh clams to corn fritters.'],
  ['Theodore Roosevelt',
   'Congaree',
   'Crater Lake',
   'Arches',
   'National Parks',
   '<strong style="font-size:inherit">Congaree</strong> National Park, located in South Carolina, is home to enormous loblolly pines and several cyprus trees well over five hundred years old.'],
  ['Micajah Autry',
   'James Bonham',
   'Jim Bowie',
   'Davey Crockett',
   'Died at the Alamo',
   'James <strong style="font-size:inherit">Bonham</strong>, at age 29, is believed to have died while manning one of the canons in the interior of the Alamo chapel.'],
  ['The Nutbush',
   'Batusie',
   'Pop, Lock, and Drop It',
   'Tango',
   'Dances',
   'The <strong style="font-size:inherit">Batusie</strong> was a go-go dance invented for the Batman television series.'],
  ['<em style="font-size:inherit">The Browning Version</em>',
   '<em style="font-size:inherit">Children of a Lesser God</em>',
   '<em style="font-size:inherit">Good Bye, Mr. Chips</em>',
   '<em style="font-size:inherit">To Sir with Love</em>',
   'Movies about Teachers',
   '<strong style="font-size:inherit"><em style="font-size:inherit">Good Bye, Mr. Chips</em></strong> was once parodied as \'Piss Off, Mr. Chips\'.'],
  ['Fork',
   'Board',
   'Knight',
   'Bishop',
   'Chess Terms',
   'Chessmen collected from the Yakutat people in Alaska bear no resemblance to European chessmen and likely belong to a chess tradition coming from Siberia.'],
  ['Wild',
   'Shade Grown',
   'Turkish',
   'Brightleaf',
   'Types of Tobacco',
   '<strong style="font-size:inherit">Shade Grown</strong> tobacco, also known as Connecticut Shade Grown Tobacco, is grown inside tents to shield it from natural sunlight.'],
  ['Atlantic',
   'Kentucky',
   'Baltic',
   'Park Place',
   '<em style="font-size:inherit">Monopoly</em> Properties',
   'The three most landed on properties in the classic <em style="font-size:inherit">Monopoly</em> game are <span style="font-variant:small-caps; font-size:inherit;">Illinois Street</span>, <span style="font-variant:small-caps; font-size:inherit;">Go</span>, and <span style="font-variant:small-caps; font-size:inherit;">B&O Railroad</span>.'],
  ['Turtle',
   'Yard-long',
   'Navy',
   'Garbanzo',
   'Beans',
   'Other beans are Lima, Mung, Moth, and Velvet.'],
  ['Linda Darnell',
   'Yvonne De Carlo',
   'Betty Davis',
   'Katherine Hepburn',
   'Lovers of Howard Hughes',
   'Howard Hughes once became so obsessed with the 1958 film, <em style="font-size:inherit">Ice Station Zebra</em>, that he had it run on a continuous loop and watched it 150 times.'],
  ['Gumma',
   'Boppa',
   'Nonny',
   'Pee-Paw',
   'Nicknames for Grandparents',
   '33% of grandparents have been married more than once and 38% have sex at least twice a week.'],
  ['Asa',
   'Ahab',
   'Saul',
   'David',
   'Jewish Kings',
   'Other Jewish Kings include Solomon, Aristobulus II, and Herod the Great.'],
  ['Negra Muerta',
   'Fuji',
   'Pelee',
   'Krakatoa',
   'Volcanos',
   'Volcanos are classified as Active, Dormant, or Extinct.'],
  ['Lancastria',
   'Indianapolis',
   'Edmund Fitzgerald',
   'Titanic',
   'Sunken Ships',
   'The <strong style="font-size:inherit">Edmund Fitzgerald</strong> was ironically known as the <strong style="font-size:inherit">Titanic</strong> of the Great Lakes.'],
  ['Pharaoh',
   'Army',
   'Fire',
   'Carpenter',
   'Types of Ants',
   'A mixture of equal parts bleach and water is known to reduce the pain and swelling of <strong style="font-size:inherit">fire</strong> ant bites.'],
  ['Burr',
   'Ivy League',
   'Fade',
   'French Twist',
   'Hair Styles',
   'An <strong style="font-size:inherit">Ivy League</strong>, also known as a Harvard Clip or Princeton, is a type of crew cut long enough to style with a side part.'],
  ['Snoring Rail',
   'Northern Cassowary',
   'Little Spotted Kiwi',
   'Ostrich',
   'Flightless Birds',
   'The call of the <strong style="font-size:inherit">Snoring Rail</strong> is a short wheeze followed by a distinctive snoring <em style="font-size:inherit">ee-orrrr</em>.  A deep <em style="font-size:inherit">hmmmm</em> sound has also been recorded.'],
  ['Christmas',
   'Banana',
   'Rice',
   'Yorkshire',
   'Types of Pudding',
   'August 9th is national <strong style="font-size:inherit">Rice</strong> Pudding Day.'],
  ['Humble High School',
   'Kansas State University',
   'Villanova University',
   'Kentucky University',
   'Colleges with a Wildcat Mascot',
   'Worldwide, real Wildcats have been known to consume midday gerbils, monitor lizards, antelope fawns and thin-toed ground squirrels.'],
  ['Jack Paar',
   'Benedict XVI',
   'Roger Ailes',
   'Richard Nixon',
   'Resigned',
   '<strong style="font-size:inherit">Jack Paar</strong> overcame a stuttering problem as a child to become a seminal figure in talk show history.'],
  ['White Horse',
   'Red Horse',
   'Black Horse',
   'Pale Horse',
   'Mounts of the Four Horsemen of the Apocalypse',
   'Death, who rides the <strong style="font-size:inherit">Pale Horse</strong>, is given the authority to kill one fourth of the population of the earth.'],
  ['Bora',
   'Mistral',
   'Dust Devil',
   'Sirocco',
   'Types of Wind',
   '<strong style="font-size:inherit">Dust Devil</strong>s on Mars can grow several times larger than Earth\'s <strong style="font-size:inherit">dust devil</strong>s and pose a concern for Martian rovers.'],
  ['Soursop',
   'Jujubee',
   'Date',
   'Watermelon',
   'Types of Fruit',
   'With an aroma similar to pineapple, <strong style="font-size:inherit">soursop</strong> has been described as having a combination of strawberry, apple, and sour citrus flavor notes.'],
  ['Philip the Arab',
   'Pertinax',
   'Hadrian',
   'Tiberius',
   'Roman Emperors',
   '<strong style="font-size:inherit">Philip the Arab</strong> was betrayed and killed by his father at the Battle of Verona in September 249 <span style="font-variant:small-caps; font-size:inherit;">AD</span> following a rebellion led by his successor, Gaius Messius Quintus Decius.'],
  ['Howard Stern',
   'Nikola Tesla',
   'Tom Cruise',
   'Howard Hughes',
   'Germaphobes',
   'Mysophobia is an anxiety disorder that results in constant hand washing.'],
  ['<em style="font-size:inherit">Nixon in China</em>',
   '<em style="font-size:inherit">A Midsummer Night\'s Dream</em>',
   '<em style="font-size:inherit">Fidelio</em>',
   '<em style="font-size:inherit">Rigoletto</em>',
   'Operas',
   'Richard Nixon (baritone), Pat Nixon (soprano), Chou-En-lai (baritone), Mao Tse-Tung (tenor) and Henry Kissinger (bass) are all characters in the opera <strong style="font-size:inherit">Nixon in China</strong>.'],
  ['Funk',
   'Truth',
   'Stanton',
   'Anthony',
   'Suffragettes',
   'The woman known as Sojourner <strong style="font-size:inherit">Truth</strong> was born into slavery in New York as Isabella Baumfree in 1797.'],
  ['Moongill',
   'Black Asian',
   'California Wild',
   'Basmati',
   'Kinds of Rice',
   'All forms of Asian rice sprang from a single domestication that occurred 8,200 to 13,500 years ago in ancient China.'],
  ['Wum',
   'Emerald',
   'Michigan',
   'Victoria',
   'Lakes',
   'Lake <strong style="font-size:inherit">Wum</strong> in Cameroon, is nearby to the towns of We and Wum.'],
  ['Pop Abernathy',
   'Pushover Paige',
   'Crazy Rhoda Zimmerman',
   'Felix Unger',
   'Characters on <em style="font-size:inherit">The Odd Couple</em>',
   'The first episode of The Odd Couple TV series, "The Laundry Orgy,\'\' aired in 1970.'],
  ['Apron',
   'Hook',
   'Bunker',
   'Par',
   'Golf Terms',
   "'Golf' spelled backwards is 'flog.'"],
  ['Link',
   'Zeebo',
   'Dill',
   'Atticus',
   'Characters in the novel <em style="font-size:inherit">To Kill a Mockingbird</em>',
   '<strong style="font-size:inherit">Zeebo</strong>, son of the Finch family housekeeper Calpurnia, works for the town of Maycomb and removes Tim Johnson, the mad dog killed by <strong style="font-size:inherit">Atticus</strong>.'],
  ['Pegeen',
   'Daisy',
   'Peg',
   'Maggy',
   'Nicknames for Margaret',
   'A diminutive of Mairead, <strong style="font-size:inherit">Pegeen</strong> is the Irish form of Margaret.'],
  ['Newfoundland Dog',
   'Montresor',
   'Lenore',
   'Arthur Gordon Pym',
   'Edgar Allen Poe Characters',
   'Poe’s father David was an alcoholic who abandoned Edgar and his two siblings after the death of Edgar’s mother.'],
  ['Willett',
   'Gaynor',
   'Beame',
   'Koch',
   'Mayors of New York City',
   'Abraham <strong style="font-size:inherit">Beame</strong>, whose adult height was five feet, two inches, boxed as a flyweight growing up on New York’s Lower East Side.'],
  ['Triclosan',
   'Propylene Glycol',
   'Sodium Laurel Sulfate',
   'Flouride',
   'Toothpaste Ingredients',
   'In the movie <em style="font-size:inherit">Dr. Strangelove</em>, General Jack D. Ripper believes his "precious bodily fluids\'\' have been depleted because of a Communist-backed plot to poison Americans with <strong style="font-size:inherit">Flouride</strong>.'],
  ['Windshield Wipers',
   'Liquid Paper',
   'Circular Saw',
   'Disposable Diapers',
   'Invented by Women',
   'Bette Nesmith Graham, mother of The Monkees’ star Mike Nesmith, invented <strong style="font-size:inherit">Liquid Paper</strong> in 1956.'],
  ['Tanauan',
   'Andersonville',
   'Manzanita',
   'Auschwitz',
   'Concentration Camps',
   'The expression "Arbeit macht frei,\'\' meaning "Work shall set you free,\'\' was used in many Nazi concentration camps.'],
  ['Coarse',
   'Superfine',
   'Brown',
   'Confectioners',
   'Types of Sugar',
   'Sugar is known to produce corpulency.'],
  ['Sumac',
   'Catnip',
   'Safflower',
   'Hawaiian Pink Sea Salt',
   'Spices',
   '<strong style="font-size:inherit">Catnip</strong> contains a terpenoid called nepetalactone that affects a cat\'s olfactory epithelium.'],
  ['Frick',
   'Chandler',
   'Landis',
   'Giamatti',
   'Baseball Commissioners',
   'A.\xa0Bartlett <strong style="font-size:inherit">Giamatti</strong> was a professor of English Renaissance Literature, the President of Yale University, and the seventh Commissioner of Major League Baseball.'],
  ['Randy Spears',
   'Candy Barr',
   'Stormy Daniels',
   'Long Dong Silver',
   'Pornographic Actors',
   'According to Stephanie A. Gregory Clifford, aka "<strong style="font-size:inherit">Stormy Daniels</strong>,\'\' she met future President Donald Trump at a celebrity golf tournament where she was working a booth promoting Wicked Pictures, an adult film company.'],
  ['Melissa',
   'Anna Kournikova',
   'ILOVEYOU',
   'Storm Worm',
   'Computer Viruses',
   'Jan De Wit, creator of the <strong style="font-size:inherit">Anna Kournikova</strong> virus, which hit email servers hard by sending e-mail to contacts in the Microsoft Outlook address book, was sentenced to 150 hours of community service.'],
  ['Luke Skywalker',
   'Bob Bryan',
   'Esau',
   'Romulus',
   'Twins',
   '<strong style="font-size:inherit">Romulus</strong> and Remus, the mythological twin founders of Rome,\xa0were suckled by a wolf and fed acorns by a friendly woodpecker.'],
  ['Eva Philbin',
   'George Washington Carver',
   'Marie Curie',
   'Louis Pasteur',
   'Chemists',
   'Eva <strong style="font-size:inherit">Philbin</strong> specialized in identifying carbohydrates in seaweed as a student at University College Galway.'],
  ['Ayelbourne',
   'Number One',
   'Chekhov',
   'Spock',
   'Original Star Trek Characters',
   'Mr. <strong style="font-size:inherit">Spock</strong>’s Vulcan salute is actually a Hebrew blessing.'],
  ['Norwegian',
   'Norman',
   'Standard Modular',
   'Jumbo',
   'Types of Brick',
   'Bricks date back to 7,000 BC, making them one of the oldest known building materials.'],
  ['Green',
   'White',
   'Scarlet',
   'Mustard',
   'Characters from the game <em style="font-size:inherit">Clue</em>',
   'Madeline Kahn played Mrs. <strong style="font-size:inherit">White</strong> in the eponymous movie based on the game.'],
  ['Florida Cracker',
   'Peruvian Stepping',
   'Appaloosa',
   'Clydesdale',
   'Horse Breeds',
   '<strong style="font-size:inherit">Appaloosas</strong> can be identified by their visible sclera (the whites of their eyes) if other indicators are inconclusive.'],
  ['Sugar',
   'Traffic',
   'Waffle',
   'Pine',
   'Cones',
   'Children once made and played with Cone Cows, pretend animals made out of <strong style="font-size:inherit">pine</strong> cones with sticks or matches for legs.'],
  ["Adam's",
   'Rialto',
   'Brooklyn',
   'George Washington',
   'Bridges',
   '<strong style="font-size:inherit">Adam’s</strong> Bridge, a chain of limestone shoals connecting India and Sri Lanka, is approximately 3,500 years old.'],
  ['Azazel',
   'Iblis',
   'Mr. Scratch',
   'Mephistopheles',
   'Names for the Devil',
   'Mister <strong style="font-size:inherit">Scratch</strong>, or Old <strong style="font-size:inherit">Scratch</strong>, is a folk name used for the Devil in early American stories, including "The Devil and Daniel Webster\'\' by Stephen Vincent Benet.'],
  ['Eldridge Cleaver',
   'Glenn Beck',
   'Mitt Romney',
   'Marie Osmond',
   'Mormons',
   'A seminal figure of 1960’s militancy, <strong style="font-size:inherit">Eldridge Cleaver</strong> later joined the Church of Latter Day Saints and became a Republican.'],
  ['Claire Keegan',
   'John Millington Synge',
   'William Butler Yeats',
   'James Joyce',
   'Irish Writers',
   '<strong style="font-size:inherit">Yeats</strong> stuck to metaphor till the end: the words on his tombstone are[20pt'],
  ['Prince',
   'Allen',
   'Wayne',
   'Kent',
   'Superhero alter-egos',
   'Diana <strong style="font-size:inherit">Prince</strong>, aka Wonder Woman, is a founding member of the Justice League.'],
  ['Cuban Pygmy',
   'Himalayan Wood',
   'Bearded Screech',
   'Snowy',
   'Owls',
   'The <strong style="font-size:inherit">Bearded Screech Owl</strong> is an insect specialist found only in the highlands of central and western Guatemala and Chiapas.'],
  ['Neil Amdur',
   'Dodo Cheney',
   'Monica Seles',
   'Venus Williams',
   'Tennis Players',
   'At the time she was attacked by a psychotic, knife-wielding Steffi Graf fan, <strong style="font-size:inherit">Monica Seles</strong> was virtually unbeatable: from January 1991 through February 1993, she won 33 of 34 tournaments she entered.'],
  ['Caudal Peduncle',
   'Brain',
   'Swim Bladder',
   'Gill Covers',
   'Fish Parts',
   'The <strong style="font-size:inherit">caudal peduncle</strong> is the tapered region behind the dorsal and anal fins, where the caudal fin attaches to the body.'],
  ['Thar',
   'Sturt Stony',
   'Kalahari',
   'Mojave',
   'Deserts',
   'About 75% of the Thar Desert, also known as the Great India Desert, is located within India, with the remaining 25% in Pakistan.'],
  ['Toy',
   'Box',
   'Pinhole',
   'Polaroid',
   'Cameras',
   'The KODAK camera introduced in 1889 was the first box camera to become widely accepted by the public.'],
  ['Lucky',
   'Lame',
   'Donald',
   'Sitting',
   'Duck',
   'Other expressions featuring the word duck include dead duck, duck out, and duck soup.'],
  ['Compression',
   'Tube',
   'Ankle',
   'Bobby',
   'Socks',
   "The modern English word sock is derived from the Old English word 'socc,' meaning 'light slipper'."],
  ['Heart of Jesus',
   'Elephant’s Ear',
   'Lady Slipper Orchid',
   'Hemlock',
   'Poisonous Plants',
   'The poisonous Caladium Plant is alternately known as <strong style="font-size:inherit">Heart of Jesus</strong>, Angel Wings and the Texas Wonder Plant.'],
  ['Pizzo Quadro',
   'Heisenhorn',
   'Mount Blanc',
   'Matterhorn',
   'Mountains of the Alps',
   'Each of the four faces of the <strong style="font-size:inherit">Matterhorn</strong> face a distinct cardinal direction.'],
  ['Stunfisk',
   'Slugma',
   'Vulpix',
   'Picachu',
   'Pokemon Characters',
   '<strong style="font-size:inherit">Slugma</strong> is a limbless Pokemon composed of magma who neither sleeps nor stops moving.'],
  ['Pole Riding',
   'Chuckwagon',
   'Mutton Busting',
   'All-around Cowboy',
   'Rodeo Events',
   '<strong style="font-size:inherit">Mutton busting</strong>, where a youth in riding position is placed atop a sheep, is said to have been introduced to the National Western Stock Show in the 1980s.'],
  ['Incus',
   'Stapes',
   'Tympanic Canal',
   'Auditory Tube',
   'Parts of the Ear',
   'Newts, salamanders, and snakes all lack ears but can still hear.'],
  ['Jim',
   'Uncle Silas',
   'The Widow Douglas',
   'Tom Sawyer',
   'Characters in <em style="font-size:inherit">The Adventures of Huckleberry Finn</em>',
   'In <em style="font-size:inherit">The Adventures of Huckleberry Finn</em>, Mark Twain portrays <strong style="font-size:inherit">Tom Sawyer</strong>, the Harry Potter of his generation, as a warped human being.'],
  ['Zong',
   'Clotilde',
   'Jesus of Lubec',
   'La Amistad',
   'Slave Ships',
   'The Trans-Atlantic Slave Trade Database has information on almost 36,000 slaving voyages, but the actual number is estimated to have been as high as 12.5 million.'],
  ['Jigging',
   'Tackle',
   'Plug',
   'Lunker',
   'Fishing Terms',
   '<strong style="font-size:inherit">Plugs</strong>, a popular type of hard-bodied fishing lure, are known by a variety of names, including Crankbait, Wobbler, Shallow-Diver and Deep-Diver.'],
  ['Mr. Wough Wup Wuff',
   'Little Nemo',
   'Skeezix',
   'Snoopy',
   'Comic Strip Characters',
   '<strong style="font-size:inherit">Mr. Wough Wup Wuff</strong> appeared in George Herriman’s comic strip \'Krazy Kat,\' which ran from 1913-1944.'],
  ['William Tecumseh Sherman',
   'Tom Doniphon',
   'J. B. Books',
   'Sean Thornton',
   'John Wayne Characters',
   'John Wayne never served in the military because of an Occupational Deferment believed to have been filed by a third party, Republic Pictures, which had the actor under contract.'],
  ['Paper',
   'Flow',
   'Dry Cell',
   'Alkaline',
   'Batteries',
   'A <strong style="font-size:inherit">Paper</strong> Battery is an electric battery engineered to use a spacer formed largely of cellulose, the major constituent of paper.'],
  ['Beer',
   'Sponge',
   'Angel',
   'Pound',
   'Kinds of Cake',
   'The name <strong style="font-size:inherit">Pound</strong> Cake comes from the fact that the original cakes each contained one pound of butter, sugar, eggs, and flour.'],
  ['Joe Paterno',
   'Sonny Wortzik',
   'Ivan Travalian',
   'Michael Corleone',
   'Al Pacino Characters',
   'Al Pacino’s grandparents emigrated to the United States from Corleone, Sicily.'],
  ['Flour',
   'Sweet',
   'Yellow Dent',
   'Popcorn',
   'Types of Corn',
   'Corn was first domesticated by indigenous people in Southern Mexico about 10,000 years ago.'],
  ['Buckeye',
   'Gulf Fritillary',
   'Giant Swallowtail',
   'Monarch',
   'Butterflies',
   'A butterfly’s eyes are made of 6,000 lenses and can see ultraviolet light.'],
  ['Kush',
   'Punt',
   'Sinai',
   'Jerusalem',
   'Places in the Bible',
   'The kingdom of <strong style="font-size:inherit">Kush</strong> was an ancient kingdom in Nubia, located at the confluences of the Blue Nile, White Nile, and the Atbarah River.'],
  ['Popper',
   'Krishnamurti',
   'Wittgenstein',
   'Confucious',
   'Philosophers',
   'Karl <strong style="font-size:inherit">Popper</strong>’s political philosophy embraced ideas from all major democratic political ideologies and attempted to reconcile them.'],
  ['Tuscan',
   'Solomonic',
   'Doric',
   'Ionic',
   'Columns',
   'With its twisted, spiraling shafts, the <strong style="font-size:inherit">Solomonic</strong> Column is one of the more exotic column types.'],
  ['Erect-crested',
   'Chinstrap',
   'King',
   'Emperor',
   'Penguins',
   'The <strong style="font-size:inherit">Emperor</strong> Penguin is the tallest and heaviest of all living penguin species.'],
  ['Handy',
   'Frawley',
   'Holden',
   'Wallace',
   'William',
   'Vaudevillian William <strong style="font-size:inherit">Frawley</strong> played the role of Fred Mertz on the television comedy series <em style="font-size:inherit">I Love Lucy</em>.'],
  ['Talking',
   'Cajon',
   'Kettle',
   'Snare',
   'Drums',
   'The <strong style="font-size:inherit">talking</strong> drum is an hourglass-shaped drum from west Africa whose pitch can be regulated to mimic the tone and prosody of human speech.'],
  ['Baxter',
   'Champ Kind',
   'Wes Mantooth',
   'Ron Burgundy',
   'Characters in <em style="font-size:inherit">Anchorman</em>',
   'The first draft of the movie envisioned John C. Reilly as <strong style="font-size:inherit">Champ Kind</strong>.'],
  ['Helmet',
   'Stone',
   'Dungeness',
   'Hermit',
   'Crabs',
   'The largest crab in the world is the Japanese Spider Crab, which can measure up to thirteen feet across.'],
  ['Renault FT',
   'PT-91 Twardy',
   'Sherman Jumbo',
   'Abrams',
   'Tanks',
   'In 1918 the <strong style="font-size:inherit">Renault FT</strong> became the first tank in history with a “modern” configuration: a revolving turret on top and an engine compartment at the rear.'],
  ['Bogardus',
   'Christopher',
   'Delancey',
   'Wall',
   'Manhattan Streets',
   'It is likely that <strong style="font-size:inherit">Wall</strong> Street got its name from a wooden palisade built on the northern boundary of the New Amsterdam settlement to---among many things---protect against pirates and the British.'],
  ['<em style="font-size:inherit">The Thin Man</em>',
   '<em style="font-size:inherit">Holiday Inn</em>',
   '<em style="font-size:inherit">Planes, Trains and Automobiles</em>',
   '<em style="font-size:inherit">It’s a Wonderful Life</em>',
   'Christmas Movies',
   'At one point in <strong style="font-size:inherit"><em style="font-size:inherit">The Thin Man</em></strong>, Myrna Loy’s character Nora Charles admits to wanting to kill the next person who wishes her a "Merry Christmas.\'\''],
  ['Cuckoo',
   'Mason',
   'Killer',
   'Honey',
   'Bees',
   'Unlike honey bees or bumblebees, <strong style="font-size:inherit">Mason</strong> Bees are solitary: every female is fertile and makes her own nest.  There are no worker Mason Bees.'],
  ['Citrine',
   'Alexandrite',
   'Sapphire',
   'Ruby',
   'Birthstones',
   '<strong style="font-size:inherit">Alexandrite</strong> is a rare variety of the mineral chrysoberyl that changes color from\xa0bluish green\xa0in daylight to\xa0purplish red under incandescent light.'],
  ['Benjamin Guggenheim',
   'Isidor Strauss',
   'John Jacob Astor IV',
   'Captain Edward Smith',
   'Titanic Casualities',
   'Titanic\xa0is the second largest ocean liner wreck in the world, only beaten by her sister, HMHS Britannic.'],
  ['Berzelius "Buzz\'\' Windrip',
   'Adenoid Hynkel',
   'Sheldon Plankton',
   'Big Brother',
   'Fictional Dictators',
   'In reality, <strong style="font-size:inherit">Plankton</strong> cannot have an eye (as portrayed), since eyes are made of multiple cells and plankton are single celled organisms.'],
  ['Adirondack Blue',
   'Irish Lumper',
   'Rooster Red',
   'Yukon Gold',
   'Potato Varieties',
   'A general use potato, the <strong style="font-size:inherit">Rooster Red</strong> was originally bred by Harry Kehoe at the Teagasc Oak Park Recreation Center in Carlow, Ireland.'],
  ['Shell',
   'Small Magellanic Cloud',
   'Starbust',
   'Spiral',
   'Galaxy Types',
   'A galaxy is a gravitationaly bound system of stars, stellar remnants, interstellar gas, dust and dark matter.'],
  ['Armstrong Duesser McHugh (aka "Lil’ Doozy\'\')',
   'Lowell Redlegs Farquhar',
   'Jane Hathaway',
   'Jed Clampett',
   'Characters from the Television Series <em style="font-size:inherit">The Beverly Hillbilles</em>',
   '<strong style="font-size:inherit">Clampett</strong> family patriarch Jed’s late wife’s name was Rose Ellen.'],
  ['Fifty Pacer',
   'Fer-de-Lance',
   'Checkered Keelback',
   'Mamba',
   'Snakes',
   'Found in Southern China, Taiwan, Northern Vietnam, and possibly Laos, the <strong style="font-size:inherit">Fifty Pacer</strong>’s poison is so strong that many believe that any creature will die within fifty steps after being bitten.'],
  ['Leonard Frig',
   'Jean Ratelle',
   'Phil Esposito',
   'Wayne Gretzky',
   'Hockey Players',
   '<strong style="font-size:inherit">Leonard</strong> Elroy <strong style="font-size:inherit">Frig</strong> played 311 total games in the NHL with the Chicago Black Hawks, the Oakland Seals, the Cleveland Barons, and the St. Louis Blues.'],
  ['Nestor',
   'Fet',
   'Gorky',
   'Tolstoy',
   'Russian Writers',
   'Born on December 5, 1820, Afanasy <strong style="font-size:inherit">Fet</strong> is widely regarded as the finest master of lyric verse in Russian Literature.'],
  ["Pam's Delight",
   'Admiral',
   'Empire',
   'Granny Smith',
   'Apple Varieties',
   '<strong style="font-size:inherit">Granny Smith</strong> apples originated in\xa0Australia\xa0in 1868 when Maria Ann (Granny) Smith found a seedling growing by a creek on her property in the same place she would toss French crab apples grown in\xa0Tasmania.'],
  ['Motion Lotion',
   'Bambi',
   'Bear in the Bushes',
   '10-4',
   'CB Radio Terms',
   '<strong style="font-size:inherit">Motion Lotion</strong> is CB radio speak for fuel.'],
  ['Lemonades',
   'Thank You Berry Munch',
   'Samoas',
   'Trefoils',
   'Girl Scout Cookies',
   'In 2014, Oklahoman Katie Francis broke her old state record by selling more than 18,000 boxes of Girl Scout Cookies.'],
  ['Tube',
   'Butterfly',
   'Gauze',
   'Adhesive',
   'Types of Bandages',
   '<strong style="font-size:inherit">Gauze</strong> is a weave structure in which the\xa0weft yarns are arranged in pairs and are crossed before and after each warp yarn, keeping the weft firmly in place.'],
  ['Elephant',
   'Nordenfelt',
   'Blunderbuss',
   'Gatling',
   'Guns',
   'Patented in 1873, the <strong style="font-size:inherit">Nordenfelt</strong> gun featured a mechanism designed to load and fire multiple barrels by moving a single lever backwards and forwards.'],
  ['Virgil',
   'Roald Amundsen',
   'Sacagawea',
   'Moses',
   'Famous Guides',
   'Upon discovering his Israelites worshipping the Golden Calf, <strong style="font-size:inherit">Moses</strong> broke the tablets containing the Ten Commandments, burned the calf, ground it to powder, scattered it on the water and made the Israelites drink it.'],
  ['California Twirl',
   'Slip the Clutch',
   'Do-Si-Do',
   'Promenade',
   'Square Dancing Terms',
   'To "<strong style="font-size:inherit">slip the clutch</strong>\'\' means to let go of one’s partner.'],
  ['Weir',
   'Pump Capacity',
   'Skimmer',
   'Chlorine',
   'Swimming Pool Terms',
   'A <strong style="font-size:inherit">Weir</strong> is the small floating "door\'\' on the side of the <strong style="font-size:inherit">Skimmer</strong> toward which water flows.'],
  ['Wagon Wheel Drill',
   'Railbird',
   'English',
   'Scratch',
   'Pool Terms',
   'A <strong style="font-size:inherit">Wagon Wheel Drill</strong> is a position control drill where the shooter tries to send the cue ball in a wide range of directions off the same shot (like spokes radiating out from the hub of a wheel).'],
  ['Butter',
   'Batavia',
   'Boston',
   'Iceberg',
   'Lettuce',
   '<strong style="font-size:inherit">Butter</strong> lettuce has a tender texture and large, cupped leaves.'],
  ['Balbo',
   'Shenandoah',
   'Neck Beard',
   'Friendly Muttonchops',
   'Facial Hair',
   '<strong style="font-size:inherit">Friendly Muttonchops</strong> are Muttonchops connected by a moustache but not chin hair (which would make it a full beard).'],
  ['Russian Orloff',
   'Cornish',
   'Booted Bantam',
   'Rhode Island Red',
   'Chickens',
   'The <strong style="font-size:inherit">Russian Orloff</strong> chicken was named for the man who championed it as a breed, Count Alexei Grigoryevich Orloff. The bird first appeared in Persia and was distributed across Europe and Asia by the seventeenth century.'],
  ['Bull',
   'Goblin',
   'Lemon',
   'Hammerhead',
   'Sharks',
   'Stingrays are a favorite food of the <strong style="font-size:inherit">Hammerhead</strong> Shark, which uses its flattened, laterally extended head to pin the Rays down until the Ray is weak and in shock.'],
  ['Spinnaker',
   'Boom',
   'Mizzenmast',
   'Gunnel',
   'Parts of a Boat',
   'A <strong style="font-size:inherit">mizzenmast</strong> is the third mast aft on a sailing vessel having three or more masts.'],
  ['The Maldives',
   'Ecuador',
   'Indonesia',
   'Brazil',
   'Countries on the Equator',
   'In 2009, to raise awareness about climate change, the <strong style="font-size:inherit">Maldives</strong> held an underwater cabinet meeting.'],
  ['One Stroke Lower',
   'Wide Latin',
   'Cambria Body',
   'Cooper Black',
   'Fonts',
   '<strong style="font-size:inherit">Cooper Black</strong> is an ultra-bold serif typeface intended for display that was designed by Oswald Bruce Cooper in 1921.'],
  ['<em style="font-size:inherit">Mabel’s Strange Predicament</em>',
   '<em style="font-size:inherit">Limelight</em>',
   '<em style="font-size:inherit">The Great Dictator</em>',
   '<em style="font-size:inherit">Modern Times</em>',
   'Charlie Chaplin Movies',
   '<strong style="font-size:inherit">Mabel’s Strange Predicament</strong> (1914) is significant in that it marks Chaplin’s first film appearance in his Little Tramp costume.'],
  ['Chagrin',
   'Ottawa',
   'Cuyahoga',
   'Ohio',
   'Ohio Rivers',
   'It is likely that the <strong style="font-size:inherit">Chagrin</strong> River got its name as a corruption of Sieur de Seguin, the name of a French settler who established a trading post on the river.'],
  ['RB Patel',
   'Hannaford',
   'Kroger',
   'Shop Rite',
   'Supermarkets',
   'Established in the 1930’s, <strong style="font-size:inherit">RB Patel</strong> is one of Fiji’s oldest supermarket chains.'],
  ['Bastard',
   'Spadroon',
   'Two-Hilted Claymore',
   'Cutlass',
   'Swords',
   'The <strong style="font-size:inherit">Bastard</strong> Sword, or Longsword, was prevalent during the late medieval and Renaissance periods (approximately 1350-1550).'],
  ['<em style="font-size:inherit">In Hell</em>',
   '<em style="font-size:inherit">White Heat</em>',
   '<em style="font-size:inherit">Cool Hand Luke</em>',
   '<em style="font-size:inherit">Papillon</em>',
   'Prison Movies',
   'Both the book and the movie <strong style="font-size:inherit">Papillon</strong> are loosely based on the life of the only man to escape from Devil’s Island, Henri Charriere, who got his nickname from the blue butterfly tattooed across his chest.'],
  ['False',
   'Chesapeake',
   'Fundy',
   'San Fransisco',
   'Bays',
   'Large schools of Snoek, a long, thin species of Snake Mackerel, can be found in South Africa’s <strong style="font-size:inherit">False</strong> Bay.'],
  ['Saloon',
   'Garden',
   'Screen',
   'French',
   'Doors',
   'A pair of "Batwing\'\' <strong style="font-size:inherit">saloon</strong> doors operate on double-action hinges extending from chest to knee level.'],
  ['Sheet',
   'Rock',
   'Nice Weight',
   'Sweeping',
   'Curling Terms',
   'An important factor in curling is which team has the last stone advantage.'],
  ['Novello',
   'Sandler',
   'Fey',
   'Belushi',
   '<em style="font-size:inherit">Saturday Night Live</em> Cast Members',
   'Don <strong style="font-size:inherit">Novello</strong> played father Guido Sarducci, a chain-smoking priest who worked as a gossip columnist for the <em style="font-size:inherit">Vatican Inquirer</em>.'],
  ['La Voz',
   'The Sultan of Swoon',
   'Ol’ Blue Eyes',
   'The Chairman of the Board',
   'Nicknames for Frank Sinatra',
   'Frank Sinatra began his singing career in the swing era with bandleaders Harry James and Tommy Dorsey.'],
  ['Cursing a fig tree',
   'Exorcism of the Syrophoenician woman’s daughter',
   'Sun stoppage',
   'Feeding the multitudes',
   'Miracles of Jesus',
   'Legend has it that there were a number of baskets of food left over after Jesus <strong style="font-size:inherit">fed the multitude</strong>.'],
  ['Knickerbocker Glory',
   'Caramel',
   'Butterscotch',
   'American Parfait',
   'Sundaes',
   'A <strong style="font-size:inherit">Knickerbocker Glory</strong> is a layered ice cream sundae served in a  tall conical glass and eaten with a distinctive long spoon.'],
  ['Trade',
   'Peace',
   'Morgan',
   'American Silver Eagle',
   'US Silver Dollars',
   'The obverse of the <strong style="font-size:inherit">Trade</strong> Dollar features a left-facing seated Lady Liberty who extends her hand bearing an olive branch over the sea.'],
  ['Stan Lee',
   'George Eliot',
   'Theodore LeSieg',
   'Miss Manners',
   'Pen Names',
   'Comic book writer, editor, film executive producer, actor and publisher <strong style="font-size:inherit">Stan Lee</strong> (d. November 12, 2018) was born Stanley Martin Lieber on December 28, 1922.'],
  ['Maine',
   'California',
   'Montana',
   'Vermont',
   'US International Border States',
   'The Coburn Gore-Woburn Border Crossing connects the towns of Woburn, Quebec and Coburn Gore, <strong style="font-size:inherit">Maine</strong>.'],
  ['Anvil Crawler',
   'Sheet',
   'Cloud to Cloud',
   'Bolt from the Blue',
   'Variations of Lightning',
   '<strong style="font-size:inherit">Anvil Crawler</strong> Lightning, sometimes called Spider Lightning, will occasionally (and spectacularly) crawl along the underside of clouds.'],
  ['Rubber',
   'Hockey',
   'Falconry',
   'Boxing',
   'Kinds of Gloves',
   'In 1889, William Stewart Halstead, the first chief of surgery at Johns Hopkins Hospital, invented <strong style="font-size:inherit">rubber</strong> gloves in order to prevent medical staff from developing dermatitis from surgical chemicals.'],
  ['Table',
   'Pickling',
   'Flaked Sea',
   'Kosher',
   'Types of Salt',
   'The Dead Sea is 9.6 times more salty than the ocean.'],
  ['Club',
   'Claw',
   'Ball Pein',
   'Sledge',
   'Types of Hammers',
   'Its flat, often metal head allows a <strong style="font-size:inherit">sledge</strong> hammer to apply more force than other hammers of similar size.'],
  ['Pumpernickel',
   'Sticks',
   'Hard',
   'Chocolate-Covered',
   'Types of Pretzels',
   'According to the Oxford English Dictionary, the first English use of the word \'<strong style="font-size:inherit">pumpernickel</strong>\' occurred in 1756.'],
  ['Ford',
   'Guinness',
   'Fisher',
   'Hamill',
   'Star Wars Cast',
   'Mark <strong style="font-size:inherit">Hamill</strong> idolized the actor Lee Marvin, who once advised him, "Never stand when you can sit.\'\''],
  ['Black',
   'Chinese White',
   'Atlantic Spotted',
   'Bottlenose',
   'Dolphins',
   'Trainer Ric O’Brien revealed that Kathy, the dolphin who once played Flipper, when confined to a small chamber in the Miami Seaquarium, committed suicide by swimming into his arms and holding her breath.'],
  ['Epidermis',
   'Petiole',
   'Vein',
   'Stomata',
   'Parts of a Leaf',
   '<strong style="font-size:inherit">Stomata</strong> are natural openings in leaves that allow for gas exchange (water vapor, carbon dioxyde,  and oxygen).'],
  ['Snap',
   'Crackle',
   'Pop',
   'Jerk',
   'Time Derivatives of Position',
   'Other time derivatives include velocity and acceleration.'],
  ['Foxglove Pug',
   'Light Brown Apple',
   'Gypsy',
   'Luna',
   'Moths',
   'Distributed across Europe, the preferred habitat of the <strong style="font-size:inherit">Foxglove Pug</strong> is the edge of woods, glades and park landscapes, gardens and warm mountain slopes, where it feeds on Foxglove Flowers.'],
  ['Rock',
   'White',
   'Pink',
   'Brine',
   'Shrimp',
   '<strong style="font-size:inherit">Pink</strong> shrimp rank among he most commercially important shrimp species in the world.'],
  ['Pigmented',
   'Pull-up',
   'Suede',
   'Nubuck',
   'Types of Leather',
   '<strong style="font-size:inherit">Pigmented</strong> leather is surface-coated with pigment color paint and then sealed with a clear coat sealer to provide enhanced durability.'],
  ['Richard Petty 43’s',
   'Rice Krinkles',
   'Maypo',
   'Franken Berry',
   'Cereal',
   'In February 1972, <strong style="font-size:inherit">Franken Berry</strong> included an indigestible pigment that turned some children’s feces pink, a symptom referred to as "Franken Berry Stool.\'\''],
  ['Zap',
   'Grand Forks',
   'Bismark',
   'Fargo',
   'Places in North Dakota',
   'The National Guard, marching with bayonets placed, invaded the town of <strong style="font-size:inherit">Zap</strong> in May, 1969, to quell a spring break gone wrong.'],
  ['Jack Dunn’s Baby',
   'The Caliph of Clout',
   'The Big Bam',
   'The Sultan of Swat',
   'Nicknames for Babe Ruth',
   'Babe Ruth lived for a time above one of his father’s string of saloons on the site of what is now Oriole Park at Camden Yards.'],
  ['He is supernatural',
   'He invented the hamburger',
   'He invented golf',
   'He is universally beloved',
   'Propaganda about Kim Jung Il',
   'Official reports have stated that Kim Jung Il also wrote 1,500 books and six full world-class operas over a period of three years.\xa0\xa0Additionally, he had physically evolved beyond needing to defecate.'],
  ['Rubinstein',
   'Capablanca',
   'Spassky',
   'Fischer',
   'Chess Masters',
   'Widely renowned for his exceptional endgame skill and speed of play, Cuban chess master Jose Raul <strong style="font-size:inherit">Capablanca</strong> is considered by many to be one of the greatest players of all time.'],
  ['The Quest',
   'Pizza Supreme',
   'Toasted Corn',
   'Nacho Cheese',
   'Doritos Varieties',
   'When fat-laden snacks melt in the mouth, the brain thinks that the calories have disappeared as well, resulting in what food scientists call "vanishing caloric density,\'\' which tends to delay the feeling of fullness.'],
  ['Mike Todd',
   'Michael Wilding',
   'Eddie Fisher',
   'Richard Burton',
   'Married to Elizabeth Taylor',
   'Elizabeth Taylor had seven husbands but eight marriages: she married <strong style="font-size:inherit">Richard Burton</strong> twice.'],
  ['Dallas Chaparrals',
   'Pittsburgh Pipers',
   'Indiana Pacers',
   'Kentucky Colonels',
   'American Basketball Association Teams',
   'The great Connie Hawkins joined the <strong style="font-size:inherit">Pittsburgh Pipers</strong> in their inagural 1967-68 season and led the team to the ABA championship.'],
  ['Ferdinand',
   'Real Quiet',
   'Whirlaway',
   'Secretariat',
   'Kentucky Derby Winners',
   'Winner of the Triple Crown in 1941, <strong style="font-size:inherit">Whirlaway</strong> was widely known as "Mr. Longtail\'\' because of his especially long and thick tail, which would blow out behind him dramatically during races.'],
  ['French',
   'Buttery',
   'Finger',
   'Kaiser',
   'Rolls',
   'A Scandinavian tradition holds that if a boy and a girl eat from the same loaf of bread they are bound to fall in love.'],
  ['Terry',
   'Keeler',
   'Cobb',
   'Williams',
   '.400 Hitters',
   'Bill <strong style="font-size:inherit">Terry</strong>, who hit .401 for the New York Giants in 1930, never batted under .320 in the nine seasons in which he received over 500 at bats.'],
  ['Calamity Jane',
   'Sally Salisbury',
   'Erma La Douce',
   'Fantine',
   'Prostitutes',
   'A celebrated prostitute of early 18th-century London, <strong style="font-size:inherit">Sally Salisbury</strong> was the subject of a number of biographies. Among them are <em style="font-size:inherit">The Genuine History of Mrs. Sarah Pridden usually called <strong style="font-size:inherit">Sally Salisbury</strong> and Her Gallants</em>, and <em style="font-size:inherit">Authentick Memoirs of the Life Intrigues and Adventures of the Celebrated <strong style="font-size:inherit">Sally Salisbury</strong></em>.'],
  ['Sea',
   'Box',
   'Mud',
   'Snapping',
   'Types of Turtles',
   'Evidence indicates that the ancestor of the modern turtle might be the Eunotosaurus, a reptile whose wide, elongated ribs curved over its back.'],
  ['Snert',
   'Callaloo',
   'Oxtail',
   'Miso',
   'Types of Soup',
   'The earliest archaeological evidence for the consumption of soup dates back to 6,000 BC (Hippopotamus soup).'],
  ['Wart',
   'Dick',
   'Yorick',
   'Ophelia',
   'Shakespeare Characters',
   '<strong style="font-size:inherit">Wart</strong> is pressed into military service by Falstaff in <em style="font-size:inherit">Henry IV</em>, Part 2.'],
  ['Auditory',
   'Atomic',
   'Wall',
   'Cuckoo',
   'Types of Clocks',
   'The idea of using <strong style="font-size:inherit">Atomic</strong> transitions to measure time was first suggested by Lord Kelvin in 1879.'],
  ['Ghost',
   'White',
   'Bell',
   'Cayenne',
   'Types of Peppers',
   'Different <strong style="font-size:inherit">Bell</strong> pepper cultivars produce fruits of different colors, including red, yellow, orange, green, white, and purple.'],
  ['Morocco',
   'Italy',
   'France',
   'Israel',
   'Countries that Border the Mediterranean Sea',
   'A recent count put the number of islands in the Mediterranean Sea at 1,460.'],
  ['Peechi',
   'Three Gorges',
   'Hoover',
   'Grand Coulee',
   'Dams',
   'India\'s <strong style="font-size:inherit">Peechi</strong> Dam is renowned as a beautiful spot for a peaceful stroll '],
  ['Ulysses',
   'Leavenworth',
   'Lawrence',
   'Witchita',
   'Places in Kansas',
   'Jim Thorpe, James Naismith and Jim Ryun all hail from <strong style="font-size:inherit">Lawrence</strong>, Kansas.'],
  ['Sun Moo',
   'Lucian Freud',
   'N. C. Wyeth',
   'Pierre Auguste Renoir',
   'Painters',
   'Fourteen of painter <strong style="font-size:inherit">Lucian Freud</strong>\'s children have been identified, two from his first marriage and twelve by various mistresses.'],
  ['Warren Jensen',
   'Woogie',
   'Brett Favre',
   'Mary Jensen',
   'Characters in <em style="font-size:inherit">Something About Mary</em>',
   'Chris Elliott played Dom "<strong style="font-size:inherit">Woogie</strong>\'\' Woganowski, one of several characters who is obsessed with Mary.'],
  ['Tomorrowland',
   'Super Bock Super Rock',
   'Cannes',
   'Mardi Gras',
   'Festivals',
   '<strong style="font-size:inherit">Super Bock Super Rock</strong> is a rock festival in Portugal created in 1994.'],
  ['Water',
   'Heart',
   'Husk',
   'Shell',
   'Parts of a Coconut',
   'One of the earliest recorded references to a coconut occurs in the story of Sinbad in <em style="font-size:inherit">One Thousand and One Arabian Nights</em>.'],
  ['Mancini',
   'Kroc',
   'Walston',
   'Robinson',
   'Ray',
   'Ray <strong style="font-size:inherit">Walston</strong> appeared in numerous films, including South Pacific, The Sting and Of Mice and Men'],
  ['Flame',
   'Golden',
   'Thompson Seedless',
   'Muscat',
   'Raisins',
   '<strong style="font-size:inherit">Muscats</strong> are larger and sweeter in comparison to other grape varieties.'],
  ['Anna',
   'Sexes',
   'Eve',
   'Kayak',
   'Palindromes',
   '"Was it a car or a cat I saw?\'\' and "A man, a plan, a canal, Panama!\'\' are also palindromes.'],
  ['The Bible',
   '<em style="font-size:inherit">Beloved</em>',
   '<em style="font-size:inherit">1984</em>',
   '<em style="font-size:inherit">Lolita</em>',
   'Banned Books',
   'Published in the U.S. in 1958, <em style="font-size:inherit"><strong style="font-size:inherit">Lolita</strong></em> became the first book since <em style="font-size:inherit">Gone with the Wind</em> to sell 100,000 copies in its first three weeks.'],
  ['Sha-na-na',
   'Edgar Winter',
   'Janis Joplin',
   'Jimi Hendrix',
   'Woodstock Performers',
   "All four of the Woodstock organizers were in their 20's."],
  ['<em style="font-size:inherit">Byzantium</em>',
   '<em style="font-size:inherit">House of Dark Shadows</em>',
   '<em style="font-size:inherit">Bloodsucking Bastards</em>',
   '<em style="font-size:inherit">Love at First Bite</em>',
   'Vampire Movies',
   'In <strong style="font-size:inherit"><em style="font-size:inherit">Bloodsucking Bastards</em></strong>, a down on his luck cubicle worker and his slacker best friend discover that their new boss is a vampire.'],
  ['"Ferdinand the Faithful\'\'',
   '"The Girl Without Hands\'\'',
   '"Rapunzel\'\'',
   '"Cinderella\'\'',
   "Characters in Grimm's Fairy Tales",
   'In "The Girl Without Hands,\'\' a miller agrees to chop his daughter\'s hands off when the Devil threatens to take his soul.'],
  ['Bust',
   'Crash Ball',
   'Mulligrubber',
   'Banana Kick',
   'Rugby Terms',
   'A <strong style="font-size:inherit">mulligrubber</strong> is a kick directed towards the ground and forced to bounce.'],
  ['Benbecula',
   'Kirkbean',
   'Aberdeen',
   'Inverness',
   'Places in Scotland',
   '<strong style="font-size:inherit">Benbecula</strong> is an island in the Outer Hebrides in the Atlantic Ocean off the west coast of Scotland.'],
  ['Price',
   'Wunderlich',
   'Domingo',
   'Pavarotti',
   'Opera Singers',
   'Mary Violet Leontyne <strong style="font-size:inherit">Price</strong>\'s mother was a midwife with a beautiful singing voice.'],
  ['Capp',
   'Segar',
   'Crumb',
   'Schulz',
   'Cartoonists',
   'Elsie Crisler <strong style="font-size:inherit">Segar</strong> was the creator of Popeye, who first appeared in the comic strip "Thimble Theater\'\' in 1929.'],
  ['Ponder',
   'Affirm',
   'Giacomo',
   'Whirlaway',
   'Kentucky Derby Winners',
   '1949 Kentucky Derby winner <strong style="font-size:inherit">Ponder</strong> sired Needles, who won the Derby in 1956.'],
  ['Goldie Gates',
   'The Emperor of America',
   'Brainiac',
   'Mister Mxyzptlk',
   'Enemies of Superman',
   "Brainiac, one of Superman's most formidable foes, hails from the planet Colu."],
  ['<em style="font-size:inherit">Lifeboat Drill</em>',
   '<em style="font-size:inherit">Suddenly, Last Summer</em>',
   '<em style="font-size:inherit">Sweet Bird of Youth</em>',
   '<em style="font-size:inherit">The Night of the Iguana</em>',
   'Plays by Tennessee Williams',
   '<strong style="font-size:inherit"><em style="font-size:inherit">Lifeboat Drill</em></strong> is a one-act play written in 1979.'],
  ['Oak Grove',
   'Ezra Church',
   'The Wilderness',
   "Harper's Ferry",
   'Civil War Battles',
   'There was no clear winner in the Battle of <strong style="font-size:inherit">the Wilderness</strong>, an area of Virginia that is typified by tangled brush and thick woods.'],
  ['Dakadak',
   'Catalina Wine Mixer',
   'Pork Chop',
   'Whirly Bird',
   'Slang for Helicopter',
   'A <strong style="font-size:inherit">Dakadak</strong> is a large attack helicopter.'],
  ['Sara Delano Roosevelt',
   'Drumgoole',
   'Washington Square',
   'Central',
   'Manhattan Parks',
   '<strong style="font-size:inherit">Drumgoole</strong> Plaza is a public park that sits in the shadow of the Brooklyn Bridge. '],
  ['Strange',
   'Pepper',
   '<em style="font-size:inherit">Strangelove</em>',
   '"My Eyes\'\'',
   'Doctor',
   'Jackson Browne was inducted into the Rock and Roll Hall of Fame in 2004.'],
  ['Jarvis',
   'Wyatt',
   'Wyman',
   'Fonda',
   'Jane',
   'Jane <strong style="font-size:inherit">Jarvis</strong> was the New York Mets organist from 1964-1979.'],
  ['Captain Shakespeare',
   'Al Capone',
   'Rupert Pupkin',
   'Sam "Ace\'\' Rothstein',
   'Robert Deniro Roles',
   'Other Robert Deniro roles include Vito Corleone, Travis Bickle, Jake Lamotta and Max Cady.'],
  ['Daniel Berrigan',
   'Gerard Manly Hopkins',
   'St. Ignatius of Loyola',
   'Pope Francis',
   'Jesuits',
   '<strong style="font-size:inherit">St. Ignatius of Loyola</strong> was a Spanish knight, priest, and founder of the Society of Jesus, whose members are known as Jesuits.'],
  ['Abernathy',
   'Palestine',
   'Fort Hancock',
   'Amarillo',
   'Places in Texas',
   'In the movie <em style="font-size:inherit">The Shawshank Redemption</em>, Ellis Boyd "Red\'\' Redding crosses the border into Mexico at <strong style="font-size:inherit">Fort Hancock</strong>.'],
  ['Maiden',
   'Booby',
   'Saint Lucia',
   'Antigua',
   'Caribbean Islands',
   'Small and privately owned, <strong style="font-size:inherit">Maiden</strong> Island is a part of the independent nation of <strong style="font-size:inherit">Antigua</strong> and Barbuda.'],
  ['Linda',
   'Early Ruby',
   'Ranier',
   'Bing',
   'Cherries',
   'Yellow inside and out with just a splash of red color, <strong style="font-size:inherit">Ranier</strong> cherries are named after Washington state\'s largest peak, Mount <strong style="font-size:inherit">Ranier</strong>.'],
  ['Mixed',
   'Rip',
   'Neap',
   'Ebb',
   'Tides',
   '<strong style="font-size:inherit">Neap</strong> Tide is a tide in which the difference between high and low tide is the least.'],
  ['Patricia',
   'Dolley',
   'Eleanor',
   'Jacqueline',
   'First Ladies',
   '<strong style="font-size:inherit">Eleanor</strong> Roosevelt considered the day she made her school\'s field hockey team the happiest of her life. '],
  ['Card',
   'Slip',
   'Focus Mitt',
   'Hook',
   'Boxing Terms',
   'Justly celebrated for his left <strong style="font-size:inherit">hook</strong>, Joe Frazier threw an excellent but underrated jab as well.'],
  ['Crocker',
   'Brooks',
   'Ural',
   'Appalachian',
   'Mountains Ranges',
   'Mount Kinabalu, one of the highest mountains in South East Asia, is in Malaysia\'s <strong style="font-size:inherit">Crocker</strong> Mountain Range.'],
  ['Whip Chute',
   'Tiger Lily',
   'Mrs. Pruneface',
   'Mumbles',
   'Dick Tracy Villains',
   '<strong style="font-size:inherit">Tiger Lily</strong> created accidents so he could record the sounds and sell them to radio stations.'],
  ['Kid Elberfeld',
   'Swede Risberg',
   'Honus Wagner',
   'Derek Jeter',
   'Shortstops',
   'A ringleader of the 1919 Chicago Black Sox, <strong style="font-size:inherit">Swede Risberg</strong> went two for twenty five at the plate and made a series record eight errors.'],
  ['Leslie Vanderkellen',
   'Larry',
   'Darryl',
   'Darryl',
   'Characters on the Television Show <em style="font-size:inherit">Newhart</em>',
   'Larry, <strong style="font-size:inherit">Darryl</strong>, and his other brother <strong style="font-size:inherit">Darryl</strong> were played by William Sanderson, Tony Papenfuss and John Volstead.'],
  ['Flared',
   'Fitted',
   'Textured',
   'Ribbed',
   'Condoms',
   '450,000,000 million condoms are sold in the United States each year.'],
  ['Sogdianus',
   'Czolgosz',
   'Princip',
   'Booth',
   'Assassins',
   'Persian ruler <strong style="font-size:inherit">Sogdianus</strong> was reportedly an illegitimate son of Arta Xerxes.'],
  ['Extra',
   'Peppersmith',
   'Razzles',
   'Dentyne',
   'Chewing Gum',
   'Introduced in 1966, <strong style="font-size:inherit">Razzles</strong> are a candy that once chewed transforms into chewing gum.'],
  ['Shrimp Boat',
   'Burger Chef',
   'Tops Drive In',
   'Burger Queen',
   'Defunct Restaurant Chains',
   'Based in Macon, Georgia, <strong style="font-size:inherit">Shrimp Boat</strong> seafood restaurants grew to 95 stores in the Southeast from 1955-1974.'],
  ['Jump',
   'Bourbon',
   'Easy',
   'Wall',
   'Street',
   'In 1789, first President George Washington took the oath of office on a balcony of <strong style="font-size:inherit">Wall</strong> Street\'s Federal Hall.'],
  ['Antelope',
   'Colca',
   'Copper',
   'Bryce',
   'Canyons',
   'Peru\'s <strong style="font-size:inherit">Colca</strong> Canyon has twice the depth of Arizona\'s Grand Canyon.'],
  ['Cover',
   'Pocket',
   'Pitch',
   'Slant',
   'Football Terms',
   'A <strong style="font-size:inherit">Slant</strong> is any play in which a receiver goes left or right as opposed to straight ahead.'],
  ['Bandy',
   'Gaelic Football',
   'Water Polo',
   'Lacrosse',
   'Sports with a Goalie',
   '<strong style="font-size:inherit">Bandy</strong> is recognized as a precursor to ice hockey.'],
  ['Dunes',
   'Bulb Fields',
   'Portrait of Doctor Gachet',
   'Starry Night Over the Rhone',
   'Van Gogh Paintings',
   'Featuring the doctor who took care of him during the final months of his life, <strong style="font-size:inherit">Portrait of Doctor Gachet</strong> is one of Van Gogh\'s most revered paintings.'],
  ['Sugar Bag',
   'Mining',
   'Honey',
   'Bumble',
   'Bees',
   '<strong style="font-size:inherit">Mining</strong> Bees create nesting tunnels in the ground.'],
  ['Rudy Ryszczyk',
   'Grandpa Fred',
   'Farmer Ted',
   'Samantha Baker',
   'Characters in <em style="font-size:inherit">Sixteen Candles</em>',
   'Other characters include Caroline Mulford, Jake Ryan and Long Duk Dong.'],
  ['Yowie',
   'Yeren',
   'Skunk Ape',
   'Yeti',
   'Fits the Bigfoot Archetype',
   'The <strong style="font-size:inherit">Yeren</strong>, or Chinese Wildman, is described as a red-haired bipedal animal over six feet tall with a pronounced belly and buttocks.'],
  ['Franz Josef Land',
   'Barrow',
   'East Siberian Sea',
   'Arctic Ocean',
   'Places Within the Arctic Circle',
   '<strong style="font-size:inherit">Franz Josef Land</strong> is a Russian archipelago inhabited only by military personnel.'],
  ['"My Leg Hurts\'\'',
   '"Rest Very Happy\'\'',
   '"The Fox is Sliding Over the Ice\'\'',
   '"Here We Come A-wassailing\'\'',
   'Christmas Carols',
   'There is a variant of "Here We Come A-wassailing\'\' called "Here We Come A-Christmasing\'\'.'],
  ['Rat',
   'Pig',
   'Monkey',
   'Rooster',
   'Chinese Zodiac Animals',
   'According to Chinese astrology, people born in the year of the <strong style="font-size:inherit">Monkey</strong> have magnetic personalities and are witty and intelligent.'],
  ['Spiller',
   'Split',
   'Hook',
   'Gutter',
   'Bowling Terms',
   'A <strong style="font-size:inherit">Spiller</strong> is a lightly hit strike.'],
  ['Anfu',
   'Bayonne',
   'Black Forrest',
   'Canned',
   'Kinds of Ham',
   '<strong style="font-size:inherit">Anfu</strong> Ham is an ancient dry-cured ham from <strong style="font-size:inherit">Anfu</strong>, Jiangxi, China, that originated in the Qin Dynasty.'],
  ['Eve Road',
   'Shirley MacLaine',
   'Aurora Greenway',
   'Irma la Douce',
   'Shirley MacLaine Characters',
   '<strong style="font-size:inherit">Shirley MacLaine</strong> played herself in Albert Brooks\' 1991 comedy <em style="font-size:inherit">Defending Your Life</em>.'],
  ['Elie Zelcer',
   'Charlotte Delbo',
   'Otto Frank',
   'Primo Levi',
   'Holocaust Survivors',
   'Anne <strong style="font-size:inherit">Frank</strong>\'s father <strong style="font-size:inherit">Otto</strong> (1889-1980) was the only member of the family to survive the Holocaust.'],
  ['<em style="font-size:inherit">Trouble at Lake Tahoe</em>',
   '<em style="font-size:inherit">The Curse of the Black Cat</em>',
   '<em style="font-size:inherit">The Secret of the Old Clock</em>',
   '<em style="font-size:inherit">Nancy\'s Mysterious Letter</em>',
   'Nancy Drew Books',
   'Carolyn Keene is the pseudonym of the ghostwriters who wrote the Nancy Drew mystery stories for the Stratemeyer Syndicate.'],
  ['Flying Dragon',
   'Fantastic Leaf-tailed Gecko',
   'Monitor',
   'Gila Monster',
   'Lizards',
   'As a general rule, lizards cannot stand the smell of garlic.'],
  ['Spife',
   'Lobster Pick',
   'Sugar Tongs',
   'Butter Knife',
   'Utensils',
   'A combination spoon and knife, a <strong style="font-size:inherit">spife</strong> is a utensil given with international flight Aer Lingus meals.'],
  ['McGinty',
   'Gazoo',
   'Gildersleeve',
   'Depression',
   'The Great',
   'Preston Sturgess won the 1940 Academy Award for Best Original Screenplay for his political satire <em style="font-size:inherit">The Great <strong style="font-size:inherit">McGinty</strong></em>.'],
  ['Husk',
   'Tassel',
   'Silk',
   'Ear',
   'Parts of a Corn Plant',
   'The <strong style="font-size:inherit">tassel</strong> is the male part of a corn plant.'],
  ['Patagonian Opossum',
   'Bandicoot',
   'Tree Kangaroo',
   'Koala',
   'Marsupials',
   '<strong style="font-size:inherit">Bandicoots</strong> produce a snuffling sound while searching for food and grunt like pigs when the food is detected.'],
  ['Hardy',
   'Roddick',
   'Griffith',
   'Warhol',
   'Andy',
   'Actor Andy <strong style="font-size:inherit">Griffith</strong> studied music at the University of North Carolina in Chapel Hill.'],
  ['John Carter',
   'Caspian',
   'Charming',
   'Aladdin',
   'Fictional Princes',
   'Edgar Rice Burroughs\' <strong style="font-size:inherit">John Carter</strong> of Mars became a Prince upon his marriage to Princess Dejah Thoris of Helium.'],
  ['Niall of the Nine Hostages',
   'Ernie Pyle',
   'The Fallen Fifty',
   'George Armstrong Custer',
   'Died in Battle',
   '<strong style="font-size:inherit">Niall of the Nine Hostages</strong> was an Irish king said to have ruled in Northern Ireland in the late fourth and early fifth centuries.'],
  ['Bottom',
   'Rock Island',
   'Maginot',
   'Mason Dixon',
   'Line',
   'The <strong style="font-size:inherit">Maginot</strong> Line consisted of concrete fortifications, obstacles, and weapons installations built by France in the 1930\'s to deter a German invasion.'],
  ['House',
   'Horse',
   'Blue Bottle',
   'Common Midge',
   'Flies',
   'The <strong style="font-size:inherit">House</strong> Fly is found worldwide and is the most common fly found around human dwellings.'],
  ['Fan',
   'Elks',
   'Strip',
   'Golf',
   'Club',
   'The Benevolent and Productive Order of <strong style="font-size:inherit">Elks</strong> of the United States of America was formally organized on February 16, 1868, in New York City.'],
  ['Sun',
   'Brown',
   'Black',
   'Polar',
   'Bears',
   'The <strong style="font-size:inherit">Sun</strong> Bear is a shy Southeast Asian forest bear that eats insects, honey, fruit, plants, and shoots.'],
  ['<em style="font-size:inherit">Manhattan</em>',
   '<em style="font-size:inherit">Ironweed</em>',
   '<em style="font-size:inherit">The Bridges of Madison County</em>',
   '<em style="font-size:inherit">Kramer vs. Kramer</em>',
   'Meryl Streep Movies',
   'Other Meryl Streep movies include <em style="font-size:inherit">Out of Africa</em>, <em style="font-size:inherit">The Deer Hunter</em>, and <em style="font-size:inherit">Sophie\'s Choice</em>.'],
  ['Deely Bobber',
   'Fillet',
   'Yarmulke',
   'Bonnet',
   'Worn on the Head',
   'A <strong style="font-size:inherit">Deely Bobber</strong> is a novelty item consisting of a headband to which springy, colorful antennae are attached.'],
  ['Colleen Corriston',
   'Chawinga',
   'Sissi',
   'Marta',
   'Women Soccer Players',
   'Two years after leaving the small town of Esplanade, Brazil, as a fourteen year old, <strong style="font-size:inherit">Sissi</strong> began featuring with the Brazilian National Team.'],
  ['Boycott',
   'Guppy',
   'Schrapnel',
   'Pompadour',
   'Named After People',
   'The <strong style="font-size:inherit">Pompadour</strong> is a hairstyle named after Madame de Pompadour, a mistress of King Louis XV.'],
  ['Joule',
   'Celsius',
   'Kelvin',
   'Watt',
   'Measurements Named After People',
   'A <strong style="font-size:inherit">Joule</strong> is equal to the energy transferred to an object when a force of one newton acts on that object in the direction of the force\'s motion through a distance of one meter: 1J = 1N x 1m.'],
  ['Bat',
   'Eins',
   'Eitt',
   'Uno',
   'Words for the Number One',
   '<strong style="font-size:inherit">One</strong> is the 35th most commonly used word in the English language, just ahead of "all\'\'.'],
  ['Virgin',
   'Lyre',
   'Winged Horse',
   'Little Bear',
   'Constellations',
   'The International Astronomical Association recognizes 88 constellations in the sky.'],
  ['Falling Leaves',
   'Flying Fish',
   'Ground Spinner',
   'Roman Candle',
   'Fireworks',
   'Other fireworks include Dahlia, Chrysanthemum, and Tree Spider.'],
  ['It was officially opened in 1931',
   'It was modeled after two earlier buildings',
   'A B-25 Bomber crashed into it',
   'For forty one years it was the tallest building in the world.',
   'The Empire State Building',
   'The upper tower of the Empire State Building was originally designed as a mooring mast for airships.'],
  ['Confetti',
   'Nonpareils',
   'Edible Glitter',
   'Jimmies',
   'Sprinkles',
   'The <strong style="font-size:inherit">Jimmie</strong> is the popular, cylindrically shaped sprinkle.'],
  ['Garden',
   'Oscillating',
   'Traveling',
   'In-Ground',
   'Lawn Sprinklers',
   'The first US patent for "Lawn Sprinkler\'\' was awarded to J. Lessler of Buffalo, New York, in 1871.'],
  ['Binky Binkenstein',
   'Bunnicula',
   'Velveteen',
   'Bugs',
   'Fictional Rabbits',
   'Other fictional rabbits include Pupu Tupuna, Mister Zig Zag, Harvey, and Thunderbunny.'],
  ['Judy Garland',
   'Eleanor Powell',
   'Cyd Charisse',
   'Ginger Rogers',
   'Danced with Fred Astaire',
   'Of all of his partners, Fred Astaire claimed that Eleanor Powell was the "only one who put \'em down like a man.\'\' '],
  ['Caroline Herschel',
   'Edwin Hubble',
   'Nicolaus Copernicus',
   'Steven Hawking',
   'Astronomers',
   'Copernicus is famous for his heliocentric illustration of the universe.'],
  ['Black Cherry',
   'Early Girl',
   'Better Boy',
   'Beefsteak',
   'Tomato Varieties',
   'Other tomato varieties include Green Zebra, Dixie Golden Giant and Chocolate Striped.'],
  ['Princess',
   'Round',
   'Radiant',
   'Baguette',
   'Diamond Cuts',
   'Diamonds score a 10 on the Mohs scale of mineral hardness.'],
  ['Iron',
   'Dog',
   'Thimble',
   'Top Hat',
   'Monopoly Pieces',
   'When Monopoly was first introduced, top hat-wearing Mr. Monopoly was known as Rich Uncle Pennybags.'],
  ['Landau',
   'Hackney',
   'Buckboard',
   'Stagecoach',
   'Horse-Drawn Carriages',
   'Other Horse-Drawn Carriages include buggys, cabs, and gigs.'],
  ['Raw',
   'White',
   'Dark',
   'Milk',
   'Chocolate',
   'Fermented beverages made from chocolate date back to 450 BC.'],
  ['Freetown',
   'Algiers',
   'Kampala',
   'Cairo',
   'African Capitals',
   '<strong style="font-size:inherit">Freetown</strong>, the capital of Sierra Leone, was first settled in 177 by 400 former British slaves sent from London.'],
  ["Commerson's",
   'Pacific White-Sided',
   'Atlantic Spotted',
   'Bottlenose',
   'Dolphins',
   'Although widespread, most dolphin species prefer the warmer waters of the tropic zones.'],
  ['School',
   'Pediatric',
   'Case Management',
   'Emergency Room',
   'Nurses',
   'The first nursing school was established in India in 250 BC.'],
  ['A Boy and His Blob',
   'Drill Dozer',
   'Tetris',
   'Super Mario Brothers',
   'Nintendo Games',
   'Players of <strong style="font-size:inherit">A Boy and His Blob</strong> must navigate the dangerous terrain of Blobolonia. ']])
