harryPotterTup = ('Magical quadegories from the famous seven book series',
 [['Professor Binns',
   'The Wailing Widow from Kent',
   'Sir Patrick Delany-Podmore',
   'Moaning Myrtle',
   'Names of ghosts',
   ''],
  ['Sir Nicholas de Mimsy-Porpington',
   'Fat Friar',
   'The Bloody Barron',
   'The Gray Lady',
   'House Ghosts',
   ''],
  ['Dolores Umbridge', # and Mad-Eye Moody
   'Severus Snape', # and Remus Lupin
   'Gilderoy Lockhart',
   'Quirinus Quirrell',
   'Defense Against the Dark Arts Teachers',
   ''],
  ['Neville Longbottom',
   'Ron Weasley',
   'Seamus Finnegan',
   'Dean Thomas',
   'Harry Potter’s Roommates',
   ''],
  ['Veela hair',
   'Unicorn hair',
   'Dragon heartstring',
   'Phoenix feather',
   'Magical items inside of wands',
   ''],
 ['The History of Magic',
  'Potions',
  'Charms',
  'Defense Against the Dark Arts',
  'Classes at Hogwarts',
  ''],
  ['Hermione Granger',
   'Justin Finch-Fletchley',
   'Colin Creevey', # and Dennis
   'Lily Evans',
   'Muggle-Borns',
   ''],
  ['Colin Creevey',
   'Mrs. Norris',
   'Hermione Granger', #  and Penelope Clearwater
   'Justin Finch-Fletchley', # Nearly Headless Nick and
   'Victims of the Basilisk',
   ''],
  ['Pigwidgeon', # Norbert
   'Errol', #  and Crookshanks
   'Fluffy', # Hedwig and Trevor
   'Mrs. Norris', # and Scabbers
   'Pets at Hogwarts',
   ''],
  ['Gadding with Ghouls',
   'Break with a Banshee',
   'Voyages with Vampires',
   'Magical Me',
   'Titles of Lockhart’s books',
   ''],
  ['Holidays with Hags',
   'Year with the Yeti',
   'Travels with Trolls',
   'Wandering with Werewolves',
   'Titles of Lockhart’s books',
   ''],
  ['Ginny',
   'Charlie', # and Bill
   'George', # Fred and
   'Percy',
   'Ron Weasley’s Siblings',
   ''],
  ['Potions Logic', #  and The Mirror of Erised
   'Wizarding Chess',
   'Devil’s Snare', # Fluffy and
   'Flying Keys',
   "Things protecting the Sorcerer's Stone",
   ''],
  ['Care of Magical Creatures',
   'Astronomy',
   'Herbology',
   'Ancient Runes',
   'Classes at Hogwarts',
   ''],
  ['Godric Gryffindor',
   'Helga Hufflepuff',
   'Rowena Ravenclaw',
   'Salizar Sytherin',
   'Founders of Hogwarts',
   ''],
  ['Acromantula',
   'Thestrals',
   'Unicorns',
   'Centaurs',
   'Magical Creatures in the Forbidden Forest',
   ''],
  ['Flobberworms' # Thestrals and Hippogriffs
   'Blast-Ended Skrewts',
   'Cornish Pixies', # Bowtruckles
   'Werewolves', # Unicorns
   'Magical Creatures studied at Hogwarts',
   ''],
  ['Cleansweep 5',
   'Nimbus Two Thousand',
   'Nimbus Two Thousand One',
   'Firebolt',
   'Types of brooms',
   ''],
  ['Fred Weasley', # George and
   'Alicia Spinnett',
   'Katie Bell', # Angelina Johnson and
   'Oliver Wood',
   'Members of the Gryffindor Quidditch team Harry’s first year',
   ''],
  ['Angelina Johnson', # Harry Potter, Oliver Wood, and
   'Marcus Flint',
   'Cedric Diggery',
   'Roger Davies',
   'Quidditch team captains',
   ''],
  ['Harry Potter',
   'Fleur Delacour',
   'Cedric Diggery',
   'Victor Krum',
   'Triwizard Tournament Champions',
   ''],
    ['Muggle studies',
    'Arithmancy',
    'Transfiguration',
    'Divination',
    'Classes at Hogwarts',
    ''],
  ['Gryffindor',
   'Hufflepuff',
   'Slytherin',
   'Ravenclaw',
   'Hogwarts houses',
   ''],
  ['Green and Silver',
   'Red and Gold',
   'Yellow and Black',
   'Blue and Bronze',
   'House colors',
   ''],
  ['Magorian',
   'Ronan',
   'Bane',
   'Firenze',
   'Names of Centaurs',
   ''],
  ['Quaffle',
   'Snitch',
   'Bludger 1',
   'Bludger 2',
   'Quidditch Balls',
   ''],
  ['Sweddish Short-Snout',
   'Welsh Green',
   'Chinese Fireball',
   'Hugarian Horntail',
   'Types of Dragons faced in the first task of the Triwizard Tournament',
   ''],
 ['Shooting Star',
  'Comet 260',
  'Silver Arrow',
  'Cleansweep 11',
  'Types of brooms',
  ''],
  ['Fluxweed', # Leeches and
   'Lacewing flies', # Knotgrass and
   'Powdered horn of a bicorn',
   'Skin of a boomslang', # Part of the person you want to change into
   'Ingredients in Polyjuice Potion',
   ''],
  ['Sending a rogue bludger', # after him during the Quidditch match against Slytherin
   'Sealing Platform 9¾',
   'Dropping the violet pudding', # at the Dursleys’ house
   'Intercepting his summer mail', # from Hermione, Ron, and Hagrid from him
   'Ways that Dobby tries to “save” Harry from the dangers at Hogwarts',
   ''],
  ['Rictusempra',
   'Tickling Charm',
   'Tarantallegra',
   'Serpensortia',
   'Spells Harry and Malfoy use against each other in the dueling club',
   ''],
  ['Say the password Pure blood',
   'Tickle a pear',
   'Answer a question', # 'Walk in front of the tapestry of Barnabas the Barmy three times and really focus on what you need',
   'Ask it to open in Parseltongue',
   'Ways to get into protected rooms',
   ''],
  ['Harry Potter and Draco Malfoy',
   'Ron Weasley and Seamus Finnegan',
   'Neville Longbottom and Justin Finch-Fletchley',
   'Hermione Granger and Millicent Bulstrode',
   'Pairs of students practicing in the Dueling Club',
   ''],
  ['Lemon drop', #  and Sherbet Lemon',
   'Acid Pops', #  and Fizzing Whizbee',
   'Cockroach Cluster', # and Toffee Eclairs',
   'Dumbledore',
   'Passwords to enter the Headmaster’s office at Hogwarts',
   ''],
  ['Violet',
   'Phineas Nigellus Black',
   'Sir Cadogan',
   'The Fat Lady',
   'People in paintings at Hogwarts',
   ''],
  ['Snape', # and McGonagall
   'Flitwick', #Hagrid and Lupin
   'Trelawney',
   'Binns',
   'Teachers at Hogwarts',
   ''],
  ['Caput Draconis',
   'Balderdash',
   'Flibbertigibbet',
   'Fairy Lights/Lairy Fights',
   'Passwords into Gryffindor Tower',
   ''],
  ['Crystal gazing',
   'Tea leaves',
   'Palmistry',
   'Astrology',
   'Ways to see into the future',
   ''],
  ['Exploding snap',
   'Wizarding chess',
   'Gobstones',
   'Quidditch',
   'Wizarding games',
   ''],
  ['Bubotuber',
   'Mandrake',
   "Devil's Snare",
   'Venomous Tentacula',
   'Plants In Herbology Class',
   ''],
  ['The Defense Association',
   'The Anti-Umbridge League',
   'Ministry of Magic Are Morons',
   'Dumbledore’s Army',
   'Names for Defence Against The Dark Arts Group',
   ''],
 ['Baubles',
  'Dilligrout',
  'Fortuna Major',
  'Mimbulus Mimbletonia',
  'Passwords into Gryffindor Tower',
  ''],
  ['Fred Weasley',
   'George Weasley',
   'Miss Fawcett of Ravenclaw',
   'Mr. Summers of Hufflepuff',
   'Students who try to get past the age line',
   ''],
  ['Millicent Bagnold',
   'Pius Thicknesse',
   'Rufus Scrimgeour',
   'Cornelius Fudge',
   'Ministers of Magic',
   ''],
  ['Alice Longbottom', # Frank and
   'Nymphadora Tonks', # Alastor Moody
   'Kingsley Shacklebolt',
   'Rufus Scrimgeour',
   'Aurors',
   ''],
  ['Sirius Black', #  and Mad-Eye Moody
   'James Potter', # and Lily
   'Remus Lupin', # Frank Longbottom and Alice
   'Frank Longbottom', # Arthur and Molly Weasley
   'Original members of the Order of the Phoenix',
   ''],
  # ['Remus Lupin and Nymphadora Tonks',
  #  'Fleur Delacour and Arthur, Molly, Bill and Charlie Weasley',
  #  'Hestia Jones, Kingsley Shacklebolt, and Mad-Eye Moody',
  #  'Sirius Black, Severus Snape, and Minerva McGonagall',
  #  'Members of the Order of the Phoenix in the Second War against Voldemort',
  #  ''],
  ['Percival',
   'Brian',
   'Wulfric',
   'Albus',
   'Dumbledore’s names',
   ''],
  ['Percy Ignatius Weasley',
   'Cornelius Oswald Fudge',
   'Dolores Jane Umbridge',
   'Amelia Susan Bones',
   'People at Harry Potter’s Ministry hearing',
   ''],
  ['Spinner’s End',
   'Magnolia Crescent',
   'Grimmauld Place',
   'Privet Drive',
   'Names of streets',
   ''],
  ['Death Stick',
   'Elder Wand',
   'Wand of Destiny',
   'Unbeatable wand',
   'Names for the gift Death gives the first brother',
   ''],
  ['Tinworth' # in Cornwall
   'Godric’s Hollow', # in the West Country
   'Ottery St. Catchpoll', # on the south coast of England
   'Upper Flagley', # in Yorkshire
   'Names of wizarding villages',
   ''],
  ['I will look after Draco when needed.',
   'I will protect Draco.',
   'I will make the Unbreakable Vow.',
   'I will fulfill Draco’s assignment', # from the Dark Lord if and when Draco fails.
   'Snape’s promises to Narcissa Malfoy',
   '']])
